### PR TITLE
Create TODO.md

### PR DESCRIPTION
**Pull request by rscircus**

### CODE REVIEW

**Comment by rscircus** [comment]
Moving that to openAHA.

**Comment by KJSanchez** [comment]
@rscircus Where is openAHA?

**Comment by rscircus** [comment]
Hi @KJSanchez, thanks for getting in touch. For now I am working on this privately in my spare time... why are you asking? :)

**Comment by KJSanchez** [comment]
@rscircus Just curious! I'm good with python and I've worn hearing aids for years. I've always wanted to build my own. Very curious what the mha community is working on.

**Pull request closed without merging**
